# Generated by Django 3.2.9 on 2021-11-06 20:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('albums', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='albums',
            name='created_at',
        ),
    ]
